# Goal - To ensure my running application is free from OWASP Top 10 security issues

name: OWASP ZAP DAST Scan

on:
  workflow_call:

jobs:
  scan:
    runs-on: self-hosted

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Wait for services to be healthy
        run: |
          timeout 60s sh -c '
            until curl -fsS http://localhost:8070 > /dev/null; do
              echo "Waiting for WorkBoard frontend..."
              sleep 2
            done
          '

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:8070'
          fail_action: false
          allow_issue_writing: false