name: DevSecOps

on:
  push:
    branches:
      - master

jobs:

  # Code quality analysis
  code-quality:
    uses: ./.github/workflows/code-quality.yml

  # Secret scanning
  secret-scan:
    uses: ./.github/workflows/secret-scanning.yml

  # Dependency vulnerability scanning
  dependency-scan:
    uses: ./.github/workflows/dependency-scan.yml

  # Docker image security scanning
  docker-scan:
    uses: ./.github/workflows/docker-scan.yml
    secrets: inherit

  # SonarQube code analysis
  sonar-scan:
    uses: ./.github/workflows/sonarqube-scan.yml
    secrets: inherit

  # Application testing
  code-test:
    uses: ./.github/workflows/code-test.yml

  # Push images to Docker Hub
  docker-push:
    uses: ./.github/workflows/docker-push.yml
    needs: [code-quality, code-test, sonar-scan, docker-scan, dependency-scan, secret-scan]
    secrets: inherit

  # Deploy application
  deploy:
    needs: [docker-push]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  # Dynamic application security testing
  dast-scan:
    needs: [deploy]
    uses: ./.github/workflows/Dast.yml
    secrets: inherit