name: DevSecOps

on:
   push:
    branches:
      - master

jobs:
  # Code Quality / Shift Left
  code-quality:
    uses: ./.github/workflows/code-quality.yml

  # Secret Scanning using gitleaks
  secret-scan:
    uses: ./.github/workflows/secret-scanning.yml

  # Dependecy scan
  dependency-scan:
    uses: ./.github/workflows/dependency-scan.yml  

  #Docker Scan and trivay,hdolint
  docker-scan:
    uses: ./.github/workflows/docker-scan.yml
    secrets: inherit

  #Sonar scan
  sonar-scan: 
    uses: ./.github/workflows/sonarqube-scan.yml 
    secrets: inherit
   #Code tests
  code-test:
    uses: ./.github/workflows/code-test.yml    

  #push to Docker hub
  docker-push:
      uses: ./.github/workflows/docker-push.yml
      needs: [code-quality,  code-test, sonar-scan,docker-scan,dependency-scan,secret-scan ]
      secrets: inherit

   #------ CD ------  

  deploy:
    needs: [ docker-push ]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  dast-scan:
    needs: [ deploy ]
    uses: ./.github/workflows/Dast.yml
    secrets: inherit         



